# -*- coding: utf-8 -*-
"""aula_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16_KjOh1xMw-dBvlu9tCIEJYCqAP1VFjL
"""

from re import I
#Função Len -------------------------- #Lê o espaço de uma variável
# texto = 'Python'
# comprimento = len(texto)
# print(comprimento)

#Função Type-------------------------- #Mostra o tipo de dados
# z = 'Guarulhos'
# w = type(z)
# print(w)

# z = 5.5
# w = type(z)
# print(w)

# z = input('Digite um n°, um texto ou bool: ')
# w = type(z)
# print(w)

#*------------------------------ #Tipo de leitura de DADOS com input
# input('Digite um n°, um texto ou bool: ')
# int(input('Digite um n°, um texto ou bool: '))
# bool(input('Digite um n°, um texto ou bool: '))
# float(input('Digite um n°, um texto ou bool: '))

#Tranformando string em Número --------------------------------
  #int/float
# n= '123456'
# x = int(n)
# print(x+8)

# n= '1.5'
# x = float(n)
# print(x+8)

  #str
# n1 = 250
# c = str(n1)
# print(c,"Olá mundo")

#Função List -------------------------- #Converter string em uma lista ou tupla - array ou vetor ou matriz

# lista = [1,3,5,6,87,0,'Oi',5.6]
# print(lista[6])

# text = 'Boa tarde'
# lista2 = list(text)
# print(lista2)

#Tuplas se comporta como constante, não pode ser alterado

# tupla = (10,5,8,9)
# print(tupla)
# tupla =(55,5,5,5)
# print(tupla)

# list = [12,55,6]
# list2 = tuple(list)
# print(list2)

#Função range() ------------------- Cria uma sequência de números inteiros em um intervalo especificado.

# numeros = range(0,12,2)
# for i in numeros:
#     print(i)

#Função sum() ------------------- Calcule a soma de uma lista
# lista3 = [3,6,5,8]    #Boas praticas python, só usar um tipo de dado em uma lista
# soma = sum(lista3)
# print(soma)

#-------------------******

#Função min(). max() ------------------  Utilizado com lista ou tuplas

# lista4 = [5,9,8,7,6,45,3]
# print(min(lista4))
# print(max(lista4))


# text2="olamundo"  #No mim ele prioriza as letra maiusculas
# primeiro = min(text2)
# print(primeiro)


#Função sorted() ------------------------- Organiza lista de menor para maior
# lista5 = [2,56,9,8,78,1,25,36,77]
# lista6  = sorted(lista5)
# print(lista6)

# lista5 = ['a','D','d','h','w','f']
# lista6  = sorted(lista5)
# print(lista6)



#EXERCÍCIOS:    ------------------------------ * ---------------------------------------------------------

#Exercício 1: Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

# n = range(2,21,2)
# for i in n:
#   print(i)

# n1 = list(n)
# print(n1)

#Exercício 2: Escreva um programa que use a função range() para gerar os múltiplos de 5 de 5 a 50 e, em seguida, calcule e imprima a soma desses múltiplos.

# n2 = range(5,50,5)
# for i1 in n2:
#   print(i1)
# print('Soma: ',sum(n2))

#Exercício 3: Escreva um programa que use a função type() para verificar o tipo de uma variável.

# n3 = 'Alex'
# print(type(n3))

#Exercício 4: Escreva um programa que use a função print() para imprimir uma mensagem de saudação personalizada, incluindo o nome do usuário.

# saudacao = input('Digite seu nome: ')
# print('Olá, ', saudacao)

#Exercício 5: Escreva um programa que use a função range() para gerar os números ímpares de 1 a 10 e, em seguida, calcule e imprima a média desses números.

# n4 = range(1,11,2)
# for i2 in n4:
#   print(i2)

# print('Média: ',sum(n4)/len(n4))

# soma_n = sum(n4)
# print('Soma dos números: ',soma_n)

# qtd_n = len(n4)
# print('Quantidade de números: ',qtd_n)

# media_n = soma_n / qtd_n
# print('Média: ', media_n)


            #*-------------LEITURA
#https://raccoon.ninja/pt/dev-pt/calculando-a-media-dos-valores-de-uma-lista-python/

#------------------------------------------------------------ LOOP FOR - WHILE

#Loop = bloco de código, variável, sequência

#Exemplo: 01
# for i in range(1,11):  #Tabuada do 05
#   print('5x ', i,'=', 5*i)

#Exemplo: 02
# word = 'Alex'
# for n1 in word:
#   print(n1+'b')

#Exemplo: 03
# for n in range(1,10):
#         print(n*10)

#Exemplo: 03
# lista = [1,2,3]
# for i in lista:
#     if i == 2 or i== 1 or i==3:
#         print('Não faça isso')
#     else:
#         print('Faça isso')



#EXERCÍCIOS 2:    ------------------------------ * ---------------------------------------------------------


#Exercício 1: Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

# m = range(2,21,2)
# for a in m:
#     print(a)

#Exercício 2: Escreva um programa que imprima os números pares de 2 a 20.



#Exercício 3: Escreva um programa que calcule a soma dos números de 1 a 100.
# soma = 0
# n = range(1,101)

# for i in n:
#     soma += i
# print(soma)


#Exercício 4: Escreva um programa que imprima os múltiplos de 5 de 5 a 50.

# n2 = range(5,50,5)
# for i1 in n2:
#   print(i1)

#Exercício 5: Escreva um programa que peça ao usuário para digitar seu nome e imprima cada caractere do nome em uma linha separada.

# number = input('Digitar seu nome')
# for i2 in number:
#   print(i2)

i = 0
n = range(1,101)
for i in n:
    console(i)
print(sum(n))